### ISSUE TITLE
[1.x] Incorrect results in case of wrong `orderBy` column name with `limit` set

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/jdbc-storage#160]
If you build a query with the wrong `orderBy` column name and `limit` you receive unpredictable results.

For example execution of following query:
```
{
....,
"target":  {
  "type":"type..../...SomeProjection",
  "includeAll":true
},
....,
"format": {
  "orderBy": {
     "direction":"ASCENDING",
     "column":"some-column-that-doesn't-exist"
  },
  "limit":20
}
}
```
Will result in `ALL` records being returned. 

Now, this is unpredictable I would expect `error`, `warning` or even `limit`ed results but not all records.

**Comment by armiol** [comment]
Addressed in 1.9.0.
